# Generated by Django 4.0.5 on 2022-06-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='schools',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='schools',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
